docker-compose.dev.yml
frontend/package-lock.json
frontend/package.json
frontend/src/config/drought/data-formats.ts
frontend/src/details/features/damages/ReturnPeriodDamageChart.tsx
frontend/src/lib/data-map/DataMap.tsx
frontend/src/pages/GuidePage.tsx
frontend/src/sidebar/networks/DamageSourceControl.tsx
tileserver/raster/Dockerfile

- `npm audit fix` for outdated packages with security warnings.
- bump `tileserver-gl-light` to v4.
- fix any build warnings that block the CI build.
- update `caniuse-lite`.

build(deps): frontend package updates

---

frontend/package-lock.json
frontend/package.json
frontend/src/App.tsx
frontend/src/lib/nav.tsx
frontend/src/pages/map/MapPage.tsx

- switch from `Switch` to `Routes`
- new, simplified `Route` API.
- `useParams` to get map view.
- updated types.

build(frontend): update react-router-dom to v6

---

frontend/package-lock.json

Update the package lock file to the latest allowed versions of all dependencies.
Includes a bump of `@mui/x-tree-view` to 7.5.1.

build(frontend): npm update dependencies

---

frontend/src/Nav.tsx
frontend/src/Notice.tsx
frontend/src/config/drought/data-formats.ts
frontend/src/config/solutions/data-access.ts
frontend/src/details/adaptations/AdaptationsSidebar.tsx
frontend/src/details/features/FeatureSidebar.tsx
frontend/src/details/features/FeatureSidebarContent.tsx
frontend/src/details/features/adaptation/AdaptationTable.tsx
frontend/src/details/features/damages/ExpectedDamageChart.tsx
frontend/src/details/features/damages/ReturnPeriodDamageChart.tsx
frontend/src/details/solutions/SolutionsSidebar.tsx
frontend/src/map/legend/MapLegend.tsx
frontend/src/pages/GuidePage.tsx
frontend/src/pages/IntroPage.tsx
frontend/src/sidebar/SidebarContent.tsx
frontend/src/sidebar/drought/DroughtsControl.tsx
frontend/src/sidebar/drought/DroughtsSection.tsx
frontend/src/sidebar/hazards/HazardsSection.tsx
frontend/src/sidebar/networks/AdaptationControl.tsx
frontend/src/sidebar/networks/NetworkControl.tsx
frontend/src/sidebar/networks/NetworksSection.tsx
frontend/src/sidebar/regions/RegionsSection.tsx
frontend/src/sidebar/solutions/MarineSection.tsx
frontend/src/sidebar/solutions/TerrestrialSection.tsx
frontend/src/state/is-retina.ts
frontend/src/state/layers/networks.ts
frontend/src/state/layers/view-layers-params.ts
frontend/src/use-is-mobile.ts

Clean up React warnings and some of the TypeScript errors (mostly use of `any` rather than specific types.)

chore(frontend): clean up ESLint errors

---

frontend/package-lock.json
frontend/package.json
frontend/src/lib/map-shapes/shapes.tsx
frontend/tsconfig.json
frontend/vite-env.d.ts
frontend/vite.config.ts

Replace the Vite SVGR plugin with the rollup plugin, which gives us a nicer import syntax for SVG imports. Update the TS config and add `tsc` to the build.

build(frontend): replace vite-plugin-svgr with @svgr/rollup

---

frontend/eslint.config.js
frontend/src/lib/data-map/MapContextProviderWithLimits.tsx

Fix a broken `useMemo` hook, where the viewport is a new object on every render.
Set the linter to warn, not error, for 'unexpected any' errors.

fix(frontend): fix a broken useMemo hook in MapContextProviderWithLimits

---

frontend/src/state/layers/view-layers.ts

The move to vector base maps accidentally removed labels for administative regions. This restores them.

fix(frontend): restore region labels

---

docker-compose.stage.yml

Docker on a Mac builds for `linux/arm64` by default, so explicitly specify `linux/amd64` for staging deploys.

build: specify target architecture

---

frontend/src/details/adaptations/FeatureAdaptationsTable.tsx
frontend/src/index.tsx
frontend/src/lib/data-map/BaseMap.tsx
frontend/src/lib/data-map/DataMap.tsx
frontend/src/lib/map/MapBoundsFitter.tsx
frontend/src/map/MapView.tsx

- use the new `createRoot` API in React 18.
- refactor the map layers to avoid an error in React Map GL when the map first mounts (#41.)
- closes #41.

refactor(frontend): concurrent rendering in React 18

---

frontend/src/state/layers/buildings.ts
frontend/src/state/layers/labels.ts
frontend/src/state/layers/regions.ts
frontend/src/state/layers/view-layers.ts

Move view layer state to separate files for each layer type. Fetch layer state with `waitForAll` to simplify the code.

refactor(frontend): view layer state

---

frontend/src/config/assets/asset-view-layer.ts
frontend/src/config/interaction-groups.ts
frontend/src/config/regions/population-view-layer.ts
frontend/src/details/features/FeatureSidebar.tsx
frontend/src/details/solutions/SolutionsSidebar.tsx
frontend/src/lib/data-map/interactions/interaction-state.ts
frontend/src/lib/data-map/interactions/use-interactions.ts
frontend/src/lib/data-map/view-layers.ts
frontend/src/map/tooltip/TooltipContent.tsx
frontend/src/state/layers/drought.ts
frontend/src/state/layers/interaction-groups.ts
frontend/src/state/layers/marine.ts
frontend/src/state/layers/terrestrial.ts

Generalise TooltipContent with a `useTooltipLayers` hook, which supplies a map of layer IDs to their respective tooltip components and layer state. This should make it easier to add new layers, by extending the map.
Refactor interaction groups as a dynamic map. Add/remove new interactive layers by adding entries to/removing entries from `src/config/interaction-groups`.

refactor(frontend): generalise TooltipContent

---

frontend/src/config/assets/asset-view-layer.ts
frontend/src/config/interaction-groups.ts
frontend/src/config/regions/population-view-layer.ts
frontend/src/details/DeselectButton.tsx
frontend/src/details/features/FeatureSidebar.tsx
frontend/src/details/regions/RegionDetails.tsx
frontend/src/details/regions/RegionDetailsContent.tsx
frontend/src/details/solutions/SolutionsSidebar.tsx
frontend/src/lib/data-map/DataMap.tsx
frontend/src/lib/data-map/DataMapTooltip.tsx
frontend/src/lib/data-map/view-layers.ts
frontend/src/map/tooltip/TooltipContent.tsx
frontend/src/map/tooltip/content/DroughtHoverDescription.tsx
frontend/src/map/tooltip/content/RasterHoverDescription.tsx
frontend/src/map/tooltip/content/RegionHoverDescription.tsx
frontend/src/map/tooltip/content/SolutionHoverDescription.tsx
frontend/src/map/tooltip/content/VectorHoverDescription.tsx
frontend/src/state/interactions/interaction-state.ts
frontend/src/state/interactions/use-interactions.ts
frontend/src/state/layers/drought.ts
frontend/src/state/layers/marine.ts
frontend/src/state/layers/terrestrial.ts
frontend/src/state/layers/view-layers-params.ts

Build interaction layer state dynamically from the interaction group config. `hoverLayerStates` is a map of layer IDs to layer hover states and layer hover targets.
```js
const layerStates = useRecoilValue(layerHoverStates);
const { isHovered, target } = layerStates.get('hazards');
```
Move interaction state from `src/lib/data-map/interactions` to `src/state/interactions`.

refactor(frontend): interaction layer state

---

frontend/src/map/legend/RasterLegend.tsx
frontend/src/map/tooltip/TooltipContent.tsx
frontend/src/map/tooltip/content/RasterHoverDescription.tsx

Refactor raster layer metadata for tooltips and legends, so that it isn't hardcoded to hazards.

refactor(frontend): raster layer metadata

---

frontend/src/config/assets/asset-view-layer.ts
frontend/src/config/regions/population-view-layer.ts
frontend/src/state/layers/drought.ts
frontend/src/state/layers/marine.ts
frontend/src/state/layers/terrestrial.ts

Restore some existential checks that were removed in #44. Without them, the map crashes when certain layers are selected in the sidebar.

fix(frontend): layer selection crashes map

---

frontend/src/config/interaction-groups.ts
frontend/src/map/tooltip/TooltipContent.tsx

Configure tooltip components for each layer ID in `src/config/interaction-groups`, so that we can edit new layers in one place.

refactor(frontend): tooltip component config

---

frontend/src/config/hazards/HazardHoverDescription.tsx
frontend/src/config/hazards/HazardLegend.tsx
frontend/src/config/hazards/hazard-view-layer.ts
frontend/src/config/hazards/metadata.ts
frontend/src/config/interaction-groups.ts
frontend/src/lib/data-map/view-layers.ts
frontend/src/map/legend/MapLegend.tsx
frontend/src/map/legend/RasterLegend.tsx
frontend/src/map/tooltip/content/RasterHoverDescription.tsx

- Add `renderLegend` and `renderTooltip` functions to the hazards view layer.
- Refactor raster tooltips and legends to use these new functions.

refactor(frontend): raster layer renderLegend and renderTooltip

---

frontend/src/config/assets/AssetHoverDescription.tsx
frontend/src/config/drought/DroughtHoverDescription.tsx
frontend/src/config/interaction-groups.ts
frontend/src/config/regions/RegionHoverDescription.tsx
frontend/src/config/solutions/SolutionHoverDescription.tsx
frontend/src/map/tooltip/content/VectorHoverDescription.tsx

Move hover descriptions to `src/config`, so that each map layer has `config/{layer}/{layer}HoverDescription`.`

refactor(frontend): tooltip hover descriptions

---

frontend/src/config/assets/AssetHoverDescription.tsx
frontend/src/config/drought/DroughtHoverDescription.tsx
frontend/src/config/hazards/HazardHoverDescription.tsx
frontend/src/config/hazards/hazard-view-layer.ts
frontend/src/config/interaction-groups.ts
frontend/src/config/regions/RegionHoverDescription.tsx
frontend/src/config/solutions/SolutionHoverDescription.tsx
frontend/src/lib/data-map/types.ts
frontend/src/lib/data-map/view-layers.ts
frontend/src/lib/state/interactions/interaction-state.ts
frontend/src/lib/state/interactions/use-interactions.ts
frontend/src/map/tooltip/TooltipContent.tsx
frontend/src/state/interactions/interaction-state.ts

- refactor tooltip components to recieve a view layer and either a raster or vector target.
- simplify interaction group config and remove the `tooltipLayers` map.
- add the new `viewLayer.renderTooltip` method to `TooltipContent`.

refactor(frontend): tooltip components

---

frontend/src/config/assets/AssetHoverDescription.tsx
frontend/src/config/color-maps.ts
frontend/src/config/drought/DroughtHoverDescription.tsx
frontend/src/config/hazards/HazardHoverDescription.tsx
frontend/src/config/hazards/hazard-view-layer.ts
frontend/src/config/interaction-groups.ts
frontend/src/config/regions/RegionHoverDescription.tsx
frontend/src/config/solutions/SolutionHoverDescription.tsx
frontend/src/lib/data-map/types.ts
frontend/src/lib/data-map/view-layers.ts
frontend/src/map/tooltip/TooltipContent.tsx
frontend/src/state/interactions/interaction-state.ts

- remove the redundant `Component` property from raster groups.
- remove the unused `RASTER_COLOR_MAPS`.
- simplify `viewLayer.renderTooltip` for raster layers.
- add `RasterHoverDescription` and `VectorHoverDescription` interfaces for tooltips.

refactor(frontend): raster config cleanup

---

frontend/src/state/layers/view-layers.ts

Dynamic imports broke the mobile layout, so revert them for now.
- closes #58.

fix(frontend): revert dynamic view layer imports

---

.github/workflows/canary-frontend.yml

Build a canary image on pushes to main, or manually from feature branches. This might be useful for testing unreleased features in a staging environment.

build(frontend): add a canary build workflow

---

frontend/src/config/assets/asset-view-layer.ts
frontend/src/config/drought/drought-options-view-layer.ts
frontend/src/config/drought/drought-risk-view-layer.ts
frontend/src/config/interaction-groups.ts
frontend/src/config/regions/boundaries-view-layer.ts
frontend/src/config/regions/population-view-layer.ts
frontend/src/config/solutions/marine-view-layer.ts
frontend/src/config/solutions/terrestrial-view-layer.ts
frontend/src/map/tooltip/TooltipContent.tsx
frontend/src/state/interactions/interaction-state.ts
frontend/src/state/layers/modules/drought.ts
frontend/src/state/layers/modules/marine.ts
frontend/src/state/layers/modules/terrestrial.ts
frontend/src/state/layers/view-layers.ts

- move view layer definitions from `src/state` to `src/config`.
- use `viewLayer.renderTooltip` to show tooltips for interactive layers.
- remove the redundant `Component` property from vector layers.

refactor(frontend): refactor vector view layers

---

frontend/src/config/assets/asset-view-layer.ts
frontend/src/config/networks/network-view-layer.ts
frontend/src/lib/data-map/view-layers.ts
frontend/src/map/legend/MapLegend.tsx
frontend/src/state/layers/modules/networks.ts
frontend/src/state/layers/view-layers-params.ts

Add the new `viewLayer.styleParams` to asset layers, replacing the old `viewLayerParams[layer.id].styleParams`.

refactor(frontend): asset layer style params

---

frontend/src/config/view-layers/buildings/buildings-view-layer.ts
frontend/src/config/view-layers/buildings/colors.ts
frontend/src/config/view-layers/networks/colors.ts
frontend/src/config/view-layers/networks/metadata.ts
frontend/src/config/view-layers/networks/view-layers.ts

Move colour config down to individual view layers eg. `config/view-layers/buildings/colors`.

refactor(frontend): remove global config/colors

---

frontend/src/config/view-layers/hazards/HazardHoverDescription.tsx
frontend/src/config/view-layers/hazards/HazardLegend.tsx
frontend/src/config/view-layers/hazards/color-maps.ts
frontend/src/config/view-layers/hazards/hazard-view-layer.ts
frontend/src/config/view-layers/hazards/metadata.ts

Configure raster colour maps as `config/hazards/color-maps`, for consistency with other layer configs.

refactor(frontend): raster colour map config

---

frontend/eslint.config.js
frontend/package-lock.json
frontend/package.json

Code in `src/lib` shouldbe completely self-contained. This adds an ESLint rule to lint imports and error if any code is imported from outside the `src/lib` directory.
- see https://github.com/nismod/irv-frontend/pull/33

style(frontend): lint imports for the `lib` directory

---

frontend/src/Nav.tsx

Add lat, lon, zoom query params to nav links, so that they're preserved when you right click and open in a new tab.

fix(frontend): add query params to navigation links

---

frontend/src/sidebar/VisibilityToggle.tsx

Wire up the visibility toggles in the sidebar so that they expand/collapse the current section.

refactor(frontend): expand/collapse sidebar with visibility toggle

---

frontend/docs/howto.md

Update the How To document to reflect the refactored `data-layers` code structure.

docs(frontend): update howto.md

---

frontend/src/details/features/FeatureSidebar.stories.tsx
frontend/src/details/features/FeatureSidebar.tsx
frontend/src/details/regions/RegionDetailsContent.stories.tsx
frontend/src/details/solutions/SolutionsSidebar.stories.tsx

Add Recoil state to the Details sidebar stories, to simulate map feature selection in the app.

test(frontend): add details selection state to stories

---

frontend/src/data-layers/terrestrial/sidebar/landuse-tree.ts

Custom read/write functions for the land use tree (in `data-layers/terrestrial`) that write a list of visible asset layer IDs to the URL, rather than true/false values for every ID in the tree.
When we read a list of visible layers from the URL, recalculate the rest of the tree state from the checked layers.
- towards #7.

refactor(frontend): optimise land use tree URLs

---

frontend/src/App.tsx

Remove the JSON parser for URL query strings, which should remove double quotes from string values.

refactor(frontend): remove double quotes from URL query params

---

frontend/src/data-layers/networks/sidebar/hierarchy.ts
frontend/src/data-layers/networks/state/data-selection.ts
frontend/src/data-layers/terrestrial/sidebar/landuse-hierarchy.ts
frontend/src/data-layers/terrestrial/sidebar/landuse-tree.ts

Replace asset layer IDs with shorter hex strings in URLs.

refactor(frontend): shorten URLs for tree data

---

frontend/src/data-layers/networks/state/data-selection.ts
frontend/src/data-layers/terrestrial/sidebar/landuse-tree.ts

`urlSyncEffect` works in development, but doesn't always run in production when a tree control changes. Add an effect that syncs a tree's state with the URL whenever the tree changes.

fix(frontend): sync tree state with url

---

frontend/src/app/Nav.tsx
frontend/src/app/state/view.ts

Persist all map URL parameters, except for `assetsStyle`, across navigations between map views. This should keep layers like buildings and regions fixed, when you move between Exposure and Risk.

feat(frontend): persist URL state across map views

---

frontend/src/app/Nav.tsx

Some settings, like infrastructure layer style, marine visibility, and terrestrial visibility, should always use view config defaults when we change map views. This adds an array of query params that should be ignored in navigation links.

refactor(frontend): allow for ignored query params in nav links

---

frontend/src/data-layers/networks/sidebar/NetworkControl.tsx

Update the selected adaptation layer whenever the infrastructure tree changes. Only one adaptation layer can be selected at a time, so take the first matching infrastructure layer if multiple layers are checked.

feat(frontend): sync adaptation controls with infrastructure tree

---

frontend/src/data-layers/networks/sidebar/NetworkControl.tsx

Sync adaptation state with the infrastructure checkbox tree state, so that adaptation state is updated whenever the checkbox tree changes (either after a change of selection or a change of URL.)

fix(frontend): sync adaptation controls with the URL

---

frontend/src/app/sidebar/StyleSelection.tsx

Fix invalid element IDs for the style selection menus, where a function was being assigned as the ID.

fix(frontend): invalid label IDs for StyleSelection

---

frontend/src/app/sidebar/ui/params/EpochControl.tsx
frontend/src/app/sidebar/ui/params/RCPControl.tsx
frontend/src/data-layers/networks/sidebar/DamageSourceControl.tsx
frontend/src/lib/controls/ParamDropdown.tsx

Add IDs to form controls where the control's label isn't explicitly linked to its control, which makes the label invisible to assistive technology.

fix(frontend): missing labels for form controls

---

frontend/src/app/sidebar/SidebarPanel.tsx

Move the visibility toggle out of the accordian button for sidebar panels, since clickable controls cannot be nested.

fix(frontend): fix nested clickable controls

---

frontend/src/app/sidebar/SidebarPanel.tsx
frontend/src/lib/controls/accordion-toggle/ToggleSection.tsx

Add appropriate states and roles to accordions, so that each summary is linked to its content. Simplify the `ToggleSection` component.

fix(frontend): ARIA states for accordion toggles

---

frontend/package-lock.json
frontend/package.json

`tileserver-gl-light` isn't used by the frontend. The vector tileserver builds from the `maptiler/tileserver-gl` image, so we should be able to safely remove it from the package file.

build(deps): remove tileserver-gl-light

---

frontend/dev-proxy/proxy-table.docker.json

The local Docker backend runs all the services behind a proxy on localhost. This proxy table routes requests to each service.

build(dev): Dev proxy for local Docker backend

---

frontend/src/lib/state/interactions/interaction-state.ts

Changes to interaction state in #149 introduced some breaking changes to the `src/lib` library. Simplify `selectionChangeEffect` to fix linter errors and avoid an intermittent bug where `viewLayer` is undefined.

fix(frontend): simplify selectionChangeEffect

---

docker-compose.stage.yml
frontend/package-lock.json
frontend/package.json

- persist selected asset features in the page URL.
- upgrade Material UI to v6.
- minor and patch updates for other dependencies.

chore(frontend): 0.4.12

---

frontend/src/app/map/BaseMap.tsx
frontend/src/app/map/DataMap.tsx
frontend/src/app/map/MapView.tsx
frontend/src/lib/data-map/BaseMap.tsx
frontend/src/lib/data-map/DataMap.tsx

Restore the shared library map components for both `BaseMap` and `DataMap` components. App-specific state is passed into each as props.

refactor(frontend): shared library map components

---

frontend/src/data-layers/networks/state/data-selection.ts
frontend/src/data-layers/terrestrial/sidebar/landuse-tree.ts

Fix a small bug where a URL query param like `netTree=19` would be passed as a number, but the URL handling code expects all query param values to be strings.
This bug can trigger in the Adaptations view, which resets the networks tree so that only one node is selected. Sharing or reloading that URL results in a map that won't render.

fix(frontend): handle numerical query params as strings

---

frontend/src/lib/hooks/use-previous.ts

The value returned by `usePrevious` should update whenever the incoming value changes.
See the example here: https://github.com/pkpdapp-team/pkpdapp/blob/master/frontend-v2/src/hooks/usePrevious.ts

fix(frontend): usePrevious hook

---

frontend/src/app/state/layers/view-layers-params.ts
frontend/src/lib/data-map/DataMap.tsx

Get and set a view layer's selection and style state with `viewLayerParamsState.get(layerId)` and `viewLayerParamsState.set(layerId, { styleParams, selection })`.

refactor(frontend): use a Map for view layer params state

---

frontend/src/details/features/FeatureSidebar.stories.tsx
frontend/src/details/solutions/SolutionsSidebar.stories.tsx
frontend/src/lib/data-map/DataMap.tsx
frontend/src/lib/data-map/view-layers.ts

Small type fix: `viewLayer.fn`, which runs whenever we update the data map, should return a deck.gl layer, or an array of deck.gl layers.

fix(frontend): view layer render types

---

frontend/src/app/config/interaction-groups.ts
frontend/src/app/config/sections.ts
frontend/src/app/config/view-layers.ts
frontend/src/app/config/views.ts
frontend/src/app/map/legend/RasterLegend.tsx
frontend/src/app/map/legend/VectorLegend.tsx
frontend/src/app/map/tooltip/content/RasterHoverDescription.tsx
frontend/src/app/sidebar/SidebarContent.tsx
frontend/src/app/state/data-params.ts
frontend/src/data-layers/assets/data-formats.ts
frontend/src/data-layers/risks/RiskHoverDescription.tsx
frontend/src/data-layers/risks/RiskLegend.tsx
frontend/src/data-layers/risks/color-maps.ts
frontend/src/data-layers/risks/domains.ts
frontend/src/data-layers/risks/metadata.ts
frontend/src/data-layers/risks/risk-view-layer.ts
frontend/src/data-layers/risks/sidebar/RisksControl.tsx
frontend/src/data-layers/risks/sidebar/RisksSection.tsx
frontend/src/data-layers/risks/source.ts
frontend/src/data-layers/risks/state/layer.ts
frontend/src/data-layers/risks/styles.ts
frontend/src/lib/helpers.ts

New raster layer showing aggregated risk values for:
- variables: "exposure value", "population affected", "loss GDP", "demand affected".
Includes:
- New aggregated risk map layer and params in `src/state/layers/modules/risks`.
- New config in `src/config/risks`. Parameters defined in `src/config/risks/domains`.
- New sidebar controls in `src/sidebar/risks`.
- New legends and tooltips in `src/config/risks`.
- Makes a start on generic formats for data values eg. financial or population.
- towards #8.

feat(frontend): aggregated risk map layer (risk hotspots)

---

frontend/src/app/map/DataMap.tsx

Add an effect to update shared view layer state when layer states change. Otherwise, changes to the sidebar won't be rendered on the map.

fix(frontend): shared view layer state

---

frontend/package.json

Run ESLint on frontend builds. This should catch breaking changes to `src/lib` in CI.
Requirements for a passing build now are:
- no TypeScript errors.
- no linting errors (including prohibited imports in `src/lib`.)
- no failing storybook stories.

build(frontend): lint frontend builds

---

frontend/src/details/features/FeatureSidebarContent.tsx
frontend/src/lib/state/interactions/interaction-state.ts

Adaptation option lists query the API via selected feature ID, so the selected asset query needs to take a feature ID as an argument. Otherwise, every item on the adaptation options list displays the currently selected feature from the map.

fix(frontend): fix feature IDs for selected feature state

---

frontend/src/app/asset-list/use-sorted-features.ts
frontend/src/app/sidebar/ui/params/DataParam.tsx
frontend/src/app/state/damage-mapping/damage-map.ts
frontend/src/app/state/damage-mapping/damage-style-params.ts
frontend/src/app/state/data-params.ts
frontend/src/data-layers/hazards/state/layer.ts
frontend/src/data-layers/networks/sidebar/AdaptationControl.tsx
frontend/src/data-layers/networks/sidebar/NetworkControl.tsx
frontend/src/data-layers/networks/sidebar/NetworksSection.tsx
frontend/src/data-layers/networks/state/layer.ts
frontend/src/data-layers/risks/state/layer.ts
frontend/src/details/adaptations/AdaptationsSidebar.stories.tsx
frontend/src/details/adaptations/AdaptationsSidebar.tsx
frontend/src/lib/controls/CustomSlider.tsx
frontend/src/lib/state/data-params.ts

Move generic data params state into `src/lib`. The aim here is that the app should be responsible for loading data params config, but the shared `lib` package should be responsible for handling data params state and updating the map.

refactor(frontend): shared data params state

---

frontend/src/data-layers/hazards/sidebar/HazardsSection.tsx

The Hazards sidebar component now needs to be connected to shared library state for data parameters (return period, epoch, and RCP.)

fix(frontend): hazard data params

---

frontend/src/lib/state/data-params.ts

Fix a small bug where default options weren't set correctly for sidebar data parameters.

fix(frontend): default data param options

---

frontend/src/lib/state/data-params.ts

Simplify initial data params state, walking through the loaded config, setting default values and options for each parameter.

refactor(frontend): initial data params state

---

frontend/src/data-layers/networks/sidebar/NetworkControl.tsx

Remove a couple of lines that prevent the default adaptation sector from being changed.
- fixes #194.

fix(frontend): adaptation options params state

---

frontend/src/app/sidebar/ui/LayerLabel.tsx
frontend/src/app/state/zoom.ts

Remove `app/state/zoom`, which isn't used anywhere, and link checkbox trees to `mapViewState.zoom`, from the shared data map library.
- fixes #195.
https://github.com/user-attachments/assets/d205d474-d950-493a-a552-cfa5067b375d

fix(frontend): zoom visibility labels in checkbox trees

---

frontend/src/data-layers/networks/sidebar/NetworkControl.tsx

A small custom hook that updates adaptation parameters when the infrastructure checkbox tree changes. This keeps the Adaptation view in sync with changes to selected infrastructure layers in the Exposure and Risk views.

refactor(frontend): useSyncAdaptationParameters hook

---

frontend/src/lib/data-map/DataMap.tsx

Sometimes, the map hover interaction is invoked before `deckRef.current` has been set. This adds a check for the deckGL deck before invoking the hover and click interactions.

fix(frontend): null refs in hover interactions

---

frontend/src/lib/data-map/DataMap.tsx

A fix for a small bug where the data map layer state doesn't always reflect the URL state, on page load.

fix(frontend): save view layers when DataMap renders

---

backend/backend/app/main.py
backend/backend/app/schemas.py
backend/backend/db/database.py

- fix linter errors.
- rename `Session` to `SessionLocal`, to avoid confusion with the built-in `Session`.

style(backend): lint the backend

---

frontend/src/app/Nav.tsx
frontend/src/app/map/BaseMap.tsx
frontend/src/lib/data-map/BaseMap.tsx
frontend/src/lib/sidebar/ui/LayerLabel.tsx
frontend/src/lib/state/map-view/map-url.ts
frontend/src/lib/state/map-view/map-view-state.ts

Refactor the base map so that map zoom state is handled in `lib/state/map-view`. Initial map state and style is configured in `app/config/map-view` and passed into the base map. `lib/data-map/BaseMap` is now responsible for updating the map when zoom parameters change.

refactpr(frontend): shared map zoom state

---

frontend/src/lib/data-loader/data-loader-manager.ts

A small refactor to `DataLoaderManager`, storing active data loaders in a Map.

refactor(frontend): store data loaders in a Map

---

frontend/src/lib/data-loader/data-loader-manager.ts
frontend/src/lib/data-loader/data-loader.ts
frontend/src/lib/deck/layers/data-loader-layer.ts

- `DataLoaderManager`: split `getDataLoader` into `getDataLoader` and `registerDataLoader`.
- `DataLoader`: add `hasData` property to check if the loader is empty.
- `DataLoaderLayer`: check if a layer has data before triggering the default behaviour (load data for all feature IDs in a tile.)

refactor(frontend): data loader management

---

frontend/src/app/map/tooltip/content/VectorHoverDescription.tsx
frontend/src/lib/map/tooltip/content/VectorHoverDescription.tsx

A small fix for tooltips. View layer params can be loaded in from `lib/state/layers`.

refactor(frontend): tooltip view layer params

---

frontend/src/app/state/layers/view-layers.ts

Fix a small glitch where the map suspends and blinks when loading a new layer. The fix is to use a Loadable while new layer state loads.

fix(frontend): remove Suspense from view layer state

---

docker-compose.stage.yml
frontend/package-lock.json
frontend/package.json

- refactor: `lib/data-map/layers/assets` now holds generic asset layer code.
- refactor: tooltip code is now in `lib/map/tooltip`.
- fix: the map no longer suspends while switching between layers, which caused it to blink in the browser.

chore(frontend): 0.4.19

---

frontend/src/data-layers/hazards/state/data-selection.ts
frontend/src/lib/state/sections.ts

`urlSyncEffect` isn't writing sidebar section visibility states or hazard visibility states to URL params. This commit adds effects which manually write to the URL whenever these states change.

fix(frontend): write section visibility states to URL

---

docker-compose.stage.yml
frontend/package-lock.json
frontend/package.json

- fix: sidebar visibility params in the URL.
- build: frontend now builds with Vite 6.
- fixes for linter warnings.

chore(frontend): 0.4.21

---

pixel_driller/Dockerfile

Build with `python:3.12-slim` for a smaller image.

build(pixel_driller): use python:3.12-slim

---

pixel_driller/Dockerfile

The `pixel-driller` image needs `g++` to build a couple of Python packages from source on Apple Macs.

build(pixel-driller): add g++ to Docker build

---

frontend/src/lib/deck/layers/data-loader-layer.ts

Fix feature IDs for data loader layers, which were broken in #266.

fix(frontend): get feature IDs for adaptation maps

---

frontend/package-lock.json
frontend/package.json

Note that `eslint-plugin-storybook` expects `typescript < 5.8.0`. See https://github.com/storybookjs/eslint-plugin-storybook/issues/193

build(deps): bump TypeScript to 5.8

---

frontend/package-lock.json
frontend/package.json

- major version upgrades for `deck.gl`, `react-map.gl`, `maplibre-gl`, `@loaders.gl`, and `@turf` packages.
- minor and patch updates for other outdated dependencies.

chore(frontend) v0.4.23

---

frontend/package-lock.json
frontend/package.json

Today's update broke the data map: raster and tile layers stopped displaying.
This PR reverts the lockfile update while I look into what broke.

build(deps): revert npm update

---

frontend/package-lock.json

Bump outdated packages to their latest allowed versions, except for deck.gl 9.1.5, which seems to break the map.

build(deps): npm update, except deck.gl

---

frontend/package-lock.json
frontend/package.json

- feat: storm raster maps showing return periods for fixed wind speeds.
- pin `deck.gl` to 9.1.4 to avoid a bug in the data map with 9.1.5.

chore(frontend): 0.4.24

---

frontend/src/lib/map/legend/use-color-map-values.ts
frontend/src/lib/map/place-search/use-place-search.ts

Refactor `react-query` fetcher functions to take `{ queryKey }` as an argument.

refactor(frontend): use react-query keys in fetcher functions

---

frontend/src/lib/map/legend/use-color-map-values.ts

- pass the stretch range to the query function, as a query parameter.
- cache fetched colormaps, to avoid repeated requests as we move around the map.

refactor(frontend): simplify colormap stretch ranges

---

frontend/eslint.config.js
frontend/package-lock.json
frontend/package.json
frontend/src/lib/api-client/ApiClient.ts
frontend/src/lib/api-client/core/ApiError.ts
frontend/src/lib/api-client/core/ApiRequestOptions.ts
frontend/src/lib/api-client/core/ApiResult.ts
frontend/src/lib/api-client/core/BaseHttpRequest.ts
frontend/src/lib/api-client/core/CancelablePromise.ts
frontend/src/lib/api-client/core/FetchHttpRequest.ts
frontend/src/lib/api-client/core/OpenAPI.ts
frontend/src/lib/api-client/core/request.ts
frontend/src/lib/api-client/core/types.ts
frontend/src/lib/api-client/index.ts
frontend/src/lib/api-client/models/Adaptation.ts
frontend/src/lib/api-client/models/ExpectedDamage.ts
frontend/src/lib/api-client/models/FeatureListItemOut_float_.ts
frontend/src/lib/api-client/models/FeatureOut.ts
frontend/src/lib/api-client/models/HTTPValidationError.ts
frontend/src/lib/api-client/models/NPVDamage.ts
frontend/src/lib/api-client/models/Page_FeatureListItemOut_float__.ts
frontend/src/lib/api-client/models/ProtectedFeatureListItem.ts
frontend/src/lib/api-client/models/ReturnPeriodDamage.ts
frontend/src/lib/api-client/models/ValidationError.ts
frontend/src/lib/api-client/models/index.ts
frontend/src/lib/api-client/services/AttributesService.ts
frontend/src/lib/api-client/services/FeaturesService.ts
frontend/src/lib/api-client/services/index.ts

v0.29 looks like the last version that was backwards compatible with `openapi-typescript-codegen`.
> Due to time limitations on my end, this project has been unmaintained for a while now. The @hey-api/openapi-ts project started as a fork with the goal to resolve the most pressing issues. going forward they are planning to maintain the OpenAPI generator and give it the love it deserves.
https://www.npmjs.com/package/openapi-typescript-codegen

build(deps-dev): migrate API client to @hey-api/openapi-ts

---

frontend/package-lock.json
frontend/package.json

Major dependency updates:
- Material UI v7.
- Migrate the API client to `@hey-api/openapi-ts` and `@hey-api/client-fetch`.
- Vega v6.
- React Router v7.

chore(frontend): 0.4.26

---

frontend/src/data-layers/risks/sidebar/RisksSection.tsx

Add `useSyncConfigState` to the hotspots sidebar section. Fixes a bug where the hotspot menus are empty in the storybook.

fix(frontend): hotspot storybook state

---

frontend/src/lib/map/tooltip/content/RasterHoverDescription.tsx

Add a ">" to the raster tooltip values when the current colour is the last entry in the colour map.

fix(frontend): add > to raster tooltip values

---

frontend/src/lib/controls/params/ParamChecklist.tsx

- `legend` must be the first child of its `fieldset`.
- remove border styling from fieldsets.

fix(a11y): fieldsets for ParamChecklist

---

etl/hotspot_layers.csv
frontend/src/data-layers/risks/color-maps.ts
frontend/src/data-layers/risks/domains.ts
frontend/src/data-layers/risks/metadata.ts
frontend/src/data-layers/risks/styles.ts

- new raster layers for the ETL pipeline
- new risk types for `data-layers/risks`.
- update `RisksControl` to hide layers if they aren't available for a sector.

feat: new transport loss hotspot maps

---

docker-compose.stage.yml

Add the terracotta ingester to the staging docker-compose file, so that you can run ingestion with:
```sh
docker compose -f docker-compose.stage.yml up raster-tile-ingester
```

build: add raster-tile-ingester to staging docker-compose

---

frontend/package-lock.json
frontend/package.json

- feat: new transport loss hotspot maps.
- feat: add `JMD/day` to supported financial units.
- refactor: tweaks and fixes for hotspot map controls.
- fix(a11y): group controls are now wrapped in fieldsets with legends.
- build(deps): upgrade to Storybook 9.
- build(deps): upgrade to the latest OpenAPI client.

chore(frontend): 0.4.29

---

frontend/src/lib/helpers.ts
frontend/src/lib/map/legend/RasterLegend.tsx
frontend/src/lib/map/tooltip/content/RasterHoverDescription.tsx

Add `numFormatFinancial`, which supports financial rates (eg. `JMD/day`.)

refactor(frontend): add numFormatFinancial for loss amounts

---

tileserver/raster/Dockerfile
tileserver/raster/requirements.txt

Add `requirements.txt` to the raster tileserver and build the image with a specific version of Cython.
Cython 3.1 came out recently and breaks the Docker build, which relies on the deprecated `numpy/math.pxd` module.

build(raster-tileserver): add requirements.txt

---

docker-compose.dev.yml
tileserver/raster/Dockerfile
tileserver/raster/requirements.txt

- pin terracotta precisely (database can change and will error between minor versions)
- let terracotta's requirements define numpy, cython versions
- bump python base container to 3.12, run apt upgrade in build step

Build raster tileserver with terracotta 0.9.1 / python 3.12

---

etl/network_tilelayers.csv

The `feature_layers_to_db` rule was failing when trying to insert records for wastewater sewer assets due to duplicate layer names in `network_tilelayers.csv`. Both sewer_gravity and sewer_pressure assets were using the same layer name `water_waste_edges`, causing database insertion conflicts.
Updated the layer names in `network_tilelayers.csv` for the problem rows:
- `water_waste_edges` → `water_waste_sewer_gravity` (for sewer_gravity asset)
- `water_waste_edges` → `water_waste_sewer_pressure` (for sewer_pressure asset)

Fix duplicate layer names causing feature_layers_to_db rule failure

---

etl/scripts/networks_to_db.py

When attempting to run the **networks_to_db** snakmake rule for layer wildcard 'coastal_protection_areas', the rule fails and raises the error "Could not find coastal_protection_areas in network layers." This error is being raised by the **networks_to_db.py** script when it attempts to execute the [get_network_layer function](https://github.com/nismod/irv-jamaica/blob/3e1741f7fb75ac41f7e2797bf780bd8d16c06059/etl/scripts/networks_to_db.py#L76). 
This is likely due to the fact that the coastal_protection_areas row is absent from the network_layers.csv and is only present in the **network_layers_areal_protection.csv**.
Within the script a new dataframe was initialised for network_layers_areal_protection.csv, 
`network_layers_areal_protection = …

bugfix: Failed execution of networks_to_db snakemake rule, missing coastal protection network layer
