nismod/irv-jamaica

frontend/package-lock.json
Update:
- `@mui/icons-material`
- `@mui/material`
- `@mui/x-tree-view`
- `@types/node`
=> build(deps): bump outdated dependencies

frontend/src/sidebar/hazards/HazardsControl.tsx
- Refactor individual hazard sections as `HazardToggleSection`.
- Use app config to generate individual hazard sections.
=> refactor(frontend): hazards sidebar

frontend/src/lib/map/DeckGLOverlay.tsx, frontend/src/map/MapView.tsx, frontend/src/map/legend/GradientLegend.tsx, frontend/src/pages/GuidePage.tsx
Run prettier and fix some ESLint errors.
=> chore(frontend): format and lint

frontend/src/config/interaction-groups.ts, frontend/src/map/legend/RasterLegend.tsx, frontend/src/map/tooltip/content/RasterHoverDescription.tsx
Move raster layer label metadata into `src/config/interaction-groups`.
=> refactor(frontend): raster metadata config

frontend/src/config/assets/AssetHoverDescription.tsx, frontend/src/config/assets/asset-view-layer.ts, frontend/src/config/drought/DroughtHoverDescription.tsx, frontend/src/config/hazards/HazardHoverDescription.tsx, frontend/src/config/hazards/hazard-view-layer.ts, frontend/src/config/interaction-groups.ts, frontend/src/config/regions/RegionHoverDescription.tsx, frontend/src/config/regions/population-view-layer.ts, frontend/src/config/solutions/SolutionHoverDescription.tsx, frontend/src/details/features/FeatureSidebar.tsx, frontend/src/details/regions/RegionDetailsContent.tsx, frontend/src/details/solutions/SolutionsSidebar.tsx, frontend/src/lib/data-map/types.ts, frontend/src/lib/data-map/view-layers.ts, frontend/src/map/tooltip/content/VectorHoverDescription.tsx, frontend/src/state/interactions/interaction-state.ts, frontend/src/state/interactions/use-interactions.ts, frontend/src/state/layers/modules/drought.ts, frontend/src/state/layers/modules/marine.ts, frontend/src/state/layers/modules/terrestrial.ts
Move shared data map types into `lib/data-map/types`.
=> refactor(frontend): data map types

frontend/src/config/assets/asset-view-layer.ts, frontend/src/config/droughtOptions/drought-options-view-layer.ts, frontend/src/config/droughtRisks/drought-risk-view-layer.ts, frontend/src/config/marine/marine-view-layer.ts, frontend/src/config/terrestrial/terrestrial-view-layer.ts, frontend/src/lib/data-map/view-layers.ts, frontend/src/map/legend/MapLegend.tsx
Add `viewLayer.renderLegend()` for vector layers.
=> refactor(frontend): vector map legends

frontend/package-lock.json
Update the frontend package lockfile with `npm upgrade --outdated`.
=> build(deps): update outdated frontend packages

frontend/src/App.tsx, frontend/src/map/BaseMap.tsx, frontend/src/pages/map/MapPage.tsx, frontend/src/pages/map/MapViewRouteSync.tsx, frontend/src/state/map-view/map-url.ts, frontend/src/state/view.ts
Store map location state as URL query parameters, so that the map can be restored when the page reloads.
=> feat(frontend): sync map location state with the url

frontend/src/Nav.tsx, frontend/src/state/sections.ts, frontend/src/state/view.ts
Sync sidebar section visibility state, overriding default section config.
=> feat(frontend): sync sidebar section visibility with url

frontend/docs/howto.md
A how-to guide to the code, based on the how-to for `nismod/irv-frontend`.
=> docs(frontend): How-to guide to the React app

frontend/src/map/tooltip/content/VectorHoverDescription.tsx
=> fix(frontend): convert numeric asset IDs to strings

frontend/src/data-layers/networks/state/data-selection.ts
Stringify network state as an array of only the checked node IDs.
=> refactor(frontend): shorten urls

frontend/.storybook/preview.tsx, frontend/src/App.tsx, frontend/src/app/Nav.stories.tsx
- add a story for the `Nav` component.
- add the theme provider and app styles to the storybook config for all stories.
=> test(frontend): App styles and Nav component story

.github/workflows/ci-build.yml, .github/workflows/storybook-tests.yml, .gitignore, frontend/package-lock.json, frontend/package.json
Build and serve the storybook in CI, then test that each story renders without errors in Webkit, Firefox and Chromium.
=> test(frontend): CI tests for storybook

frontend/src/data-layers/networks/sidebar/NetworksSection.stories.tsx
Test that the networks control only shows a warning message for the adaptations view.
=> test(frontend): test the networks control text 

.github/workflows/publish-storybook.yml
Publish the storybook to GitHub Pages.
=> test(frontend): publish the storybook

frontend/src/details/adaptations/FeatureAdaptationsTable.tsx, frontend/src/details/regions/RegionDetailsContent.tsx, frontend/src/details/solutions/SolutionsSidebarContent.tsx, frontend/src/mocks/details/solutions/mockMarineFeature.json
Fix some accessibility failures that were picked up by axe in the details sidebar components.
=> fix(frontend): details sidebar accessibility failures

frontend/src/details/features/adaptation/AdaptationSection.tsx, frontend/src/details/features/adaptation/AdaptationTable.tsx, frontend/src/details/features/damages/DamageTable.tsx, frontend/src/details/features/damages/DamagesSection.tsx, frontend/src/details/features/damages/RPDamageTable.tsx
- hierarchical heading structure, for users that navigate by heading.
- fix unlabelled combobox inputs.
- add `tabindex` to scrolling tables.
=> fix(frontend): accessibility improvements for FeatureSidebar

frontend/src/data-layers/terrestrial/sidebar/TerrestrialControl.tsx, frontend/src/lib/controls/checkbox-tree/CheckboxTreeItem.tsx, frontend/src/lib/controls/checkbox-tree/tree-node.ts
Add labels for checkbox tree items and terrestrial control sliders.
=> fix(frontend): unlabelled form controls

frontend/package-lock.json, frontend/public/mockServiceWorker.js
=> build(deps): npm update

frontend/src/details/features/FeatureSidebar.stories.tsx, frontend/src/details/regions/RegionDetails.stories.tsx, frontend/src/details/solutions/SolutionsSidebar.stories.tsx
Storybook tests for the Details sidebar stories.
=> test(frontend): add tests for Details sidebar components

frontend/src/lib/state/interactions/interaction-state.ts
- write the view layer ID and feature ID to the URL when a network asset feature is selected on the map.
- read selected view layer IDs and feature IDs from the URL when the map loads.
- restore the details sidebar selection state from any IDs stored in the URL.
With the change here, selected asset features are preserved across page loads.
https://github.com/user-attachments/assets/103a7ef6-4e75-40ac-a959-e094b2d3e2fa
=> feat(frontend): persist selected asset features in the url

frontend/src/data-layers/terrestrial/TerrestrialHoverDescription.tsx
Fix a missing terrestrial feature cell index in the hover popup.
=> fix(frontend): terrestrial feature cell index

frontend/src/lib/data-map/DataMap.tsx
Refactor the helper functions, which render the DeckGL layers, and move the `dataLoadTrigger` logic into a `useTrigger` hook.
This is a smaller refactor than #154, which won't break adaptation options.
=> refactor(frontend): refactor DataMap component

docker-compose.stage.yml, frontend/package-lock.json, frontend/package.json
- fix numerical query params.
- fix terrestrial cell IDs in mouse hover popups.
- fix missing dependency for `usePrevious` hook.
- refactor data fetching for DeckGL map layers.
- refactor shared `BaseMap` and `DataMap` components.
=> chore(frontend): 0.4.13

frontend/src/app/pages/DataPage.stories.tsx, frontend/src/app/pages/GuidePage.stories.tsx, frontend/src/app/pages/IntroPage.stories.tsx
Add stories for the home page, guide page and data page.
=> test(storybook): stories for static text pages

docker-compose.stage.yml, frontend/package-lock.json, frontend/package.json
- new feature! Aggregated risk maps in the Risk section.
- new stories for static pages (home page, data page, about page.)
- refactors and fixes for deck.gl data layers.
=> chore(frontend): 0.4.14

frontend/src/data-layers/assets/asset-view-layer.ts, frontend/src/data-layers/droughtOptions/drought-options-view-layer.ts, frontend/src/data-layers/droughtRisks/drought-risk-view-layer.ts, frontend/src/data-layers/marine/marine-view-layer.ts, frontend/src/data-layers/regions/population-view-layer.ts, frontend/src/data-layers/terrestrial/terrestrial-view-layer.ts, frontend/src/lib/data-loader/data-loader.ts, frontend/src/lib/deck/layers/data-loader-layer.ts, frontend/src/lib/deck/layers/selectable-mvt-layer.ts, frontend/src/lib/deck/layers/tile-selection-layer.ts
Replace `selectedFeatureId` with an array of `selectedFeatureIds` in all selectable MVT layers.
=> refactor(frontend): multiple selected feature IDs

frontend/src/details/features/FeatureSidebarContent.tsx, frontend/src/lib/state/interactions/interaction-state.ts
- Move the feature details query into Recoil state, so that it can be shared from `/src/lib/state/interactions`.
- Update the feature sidebar to use the shared Recoil state.
- Remove the `useFeatureDetails` hook from the feature sidebar.
=> refactor(frontend): shared asset selection state

frontend/src/lib/state/interactions/interaction-state.ts, frontend/src/lib/state/interactions/use-interactions.ts
Clean up `userInteractions` hook. Remove `useCallback`, `useMemo`, and `useEffect`.
=> refactor(frontend): useInteractions hook

docker-compose.stage.yml, frontend/package-lock.json, frontend/package.json
- new feature: allow a view layer to have more than one selected feature.
- refactor the shared library to handle view layer state.
- refactor the shared library to handle data parameters state.
- fail frontend CI builds if the linter errors.
=> chore(frontend): 0.4.15

frontend/src/app/config/sections.ts, frontend/src/app/sidebar/SidebarPanel.tsx, frontend/src/app/sidebar/StyleSelection.tsx, frontend/src/app/sidebar/VisibilityToggle.tsx, frontend/src/app/state/layers/ui/labels.ts, frontend/src/app/state/sections.ts, frontend/src/app/state/view.ts, frontend/src/data-layers/buildings/state/layer.ts, frontend/src/data-layers/droughtOptions/state/layer.ts, frontend/src/data-layers/droughtRisks/state/layer.ts, frontend/src/data-layers/hazards/state/layer.ts, frontend/src/data-layers/marine/state/layer.ts, frontend/src/data-layers/networks/sidebar/NetworksSection.tsx, frontend/src/data-layers/networks/state/data-selection.ts, frontend/src/data-layers/networks/state/layer.ts, frontend/src/data-layers/regions/state/data-selection.ts, frontend/src/data-layers/regions/state/layer.ts, frontend/src/data-layers/risks/sidebar/RisksControl.tsx, frontend/src/data-layers/risks/state/layer.ts, frontend/src/data-layers/terrestrial/state/layer.ts, frontend/src/details/DetailsSidebar.tsx, frontend/src/lib/state/sections.ts
Move common code for sections state into `src/lib`.
=> refactor(frontend): shared sidebar sections state

docker-compose.stage.yml, frontend/package-lock.json, frontend/package.json, frontend/public/mockServiceWorker.js
- fix: selected adaptation sector couldn't be changed on the map.
- fix: zoom level visibility for checkbox items now tracks the current zoom level.
- refactor: shared lib code for sidebar sections state.
- docs: ETL data transformation pipeline.
=> chore(frontend): 0.4.16

frontend/src/app/asset-list/use-sorted-features.ts, frontend/src/lib/api-client/models/Page_FeatureListItemOut_float__.ts
Run the `generate-client` script to make sure that the TypeScript client is up-to-date with the backend.
=> refactor(frontend): run generate-client

frontend/src/app/asset-list/SortedAssetTable.tsx, frontend/src/app/asset-list/use-sorted-features.ts
Store the adaptation options sorted feature list in a Recoil selector, so that it persists across page navigations. Otherwise, a potentially expensive API query is made each time the sorted asset table mounts and unmounts.
=> refactor(frontend): persistent adaptation options state

frontend/docs/structure.md
Update the structure docs with recent changes to the `app/` directory.
=> docs(frontend): update app structure docs

docker-compose.stage.yml, frontend/package-lock.json, frontend/package.json
- persist adaptation options state across view navigations.
- fix selected asset not hihglighted on page load.
- move sidebar components into shared lib.
- move map view state into shared lib.
- move sorted asset table into shared lib.
- refactor data loaders and data accessors to allow for future layers with preloaded data.
=> chore(frontend): 0.4.18

frontend/docs/structure.md
Update `structure.md` to remove `app/map/tooltip`.
=> docs(frontend): update structure docs

frontend/src/app/state/layers/view-layers.ts
Loadable view layer config breaks selected features when switching between views. This commit reverts the changes in #237 and caches view layer config in a Map instead.
=> fix(frontend): cache view layer config in a map

frontend/src/app/map/MapView.tsx
Remove `useRecoilValue` from `MapViewContent` and move it down into a child component.
- fixes #241.
=> fix(frontend): infinite loop in data map renders

docker-compose.stage.yml, frontend/package-lock.json, frontend/package.json
Bug fix release:
- fixes a bug where the map freezes if it tries to display a raster tooltip.
- fixes a bug where the selected feature is deselected by view or sidebar state changes.
=> chore(frontend): 0.4.20

frontend/package-lock.json, frontend/package.json
Bump Vite to v6 and `vite-tsconfig-paths` to v5.
=> build(deps-dev): bump Vite to 6.0.7

deploy/etc/nginx/sites-available/jamaica.infrastructureresilience.org, docker-compose.stage.yml
Add pixel-driller to the nginx config and the staging docker-compose file.
=> build: deploy pixel-driller API to staging

frontend/package.json
- feat: prototype of the Pixel Driller API. Show all the hazard data for a selected map point.
- build: dependency updates.
=> chore(frontend): 0.4.22

frontend/src/lib/deck/layers/data-loader-layer.ts
Remove some debug logs now that adaptation maps are working again.
=> fix(frontend): remove debug logs

frontend/eslint.config.js
Rules are documented at https://github.com/storybookjs/eslint-plugin-storybook/blob/main/README.md#supported-rules-and-configurations
=> style(frontend): configure ESLint Storybook plugin

frontend/package-lock.json, frontend/package.json, frontend/src/App.tsx, frontend/src/app/map/use-basemap-style.ts, frontend/src/lib/map/legend/use-color-map-values.ts, frontend/src/lib/map/place-search/MapSearchField.tsx, frontend/src/lib/map/place-search/use-place-search.ts, frontend/src/query-client.ts
- replace `use-http` with `@tanstack/react-query`.
- add a query client and provider.
- migrate from `useFetch` to `useQuery`.
=> refactor(frontend): replace useFetch with react-query

frontend/package.json
=> build(frontend): lint dev builds

frontend/package-lock.json, frontend/package.json
- build: upgrade MUI-X to 8.2.0.
- build: update dependencies.
=> chore(frontend): v0.4.27

etl/hotspot_layers.csv, frontend/src/data-layers/risks/color-maps.ts, frontend/src/data-layers/risks/domains.ts, frontend/src/data-layers/risks/risk-view-layer.ts, frontend/src/data-layers/risks/sidebar/RisksControl.tsx, frontend/src/data-layers/risks/sidebar/RisksSection.stories.tsx, frontend/src/data-layers/risks/sidebar/RisksSection.tsx, frontend/src/data-layers/risks/source.ts, frontend/src/data-layers/risks/state/layer.ts
Risk hotpsot maps grouped by infrastructure sector.
https://github.com/user-attachments/assets/14a82e87-868b-4b8c-b7b2-6a2fe8b4cdd0
=> feat(frontend): risk hotspots by sector

frontend/package-lock.json, frontend/package.json
- feat: hotspot maps by sector.
- build: dependency updates.
=> chore(frontend): v0.4.28

frontend/src/data-layers/risks/domains.ts, frontend/src/data-layers/risks/sidebar/RisksControl.tsx
- Make 'All' the first item in the dropdown menu.
- Change 'Risk' to 'Variable'.
- Hide variables that don't apply to a sector.
=> refactor(frontend): hotspots sidebar layout

frontend/.storybook/main.ts, frontend/.storybook/preview.tsx, frontend/package-lock.json, frontend/package.json, frontend/src/app/Nav.stories.tsx, frontend/src/app/pages/DataPage.stories.tsx, frontend/src/app/pages/GuidePage.stories.tsx, frontend/src/app/pages/IntroPage.stories.tsx, frontend/src/data-layers/buildings/sidebar/BuildingsSection.stories.tsx, frontend/src/data-layers/droughtRisks/sidebar/DroughtsSection.stories.tsx, frontend/src/data-layers/hazards/sidebar/HazardsSection.stories.tsx, frontend/src/data-layers/marine/sidebar/MarineSection.stories.tsx, frontend/src/data-layers/networks/sidebar/NetworksSection.stories.tsx, frontend/src/data-layers/regions/sidebar/RegionsSection.stories.tsx, frontend/src/data-layers/risks/sidebar/RisksSection.stories.tsx, frontend/src/data-layers/terrestrial/sidebar/TerrestrialSection.stories.tsx, frontend/src/details/adaptations/AdaptationsSidebar.stories.tsx, frontend/src/details/features/FeatureSidebar.stories.tsx, frontend/src/details/pixel-data/PixelData.stories.tsx, frontend/src/details/regions/RegionDetails.stories.tsx, frontend/src/details/solutions/SolutionsSidebar.stories.tsx, frontend/src/stories/Configure.mdx
Upgrade storybook with `npx storybook@latest upgrade`.
Remove `@chromatic-com/storybook` (we don't use Chromatic for visual testing and their plugin only supports Storybook 8.)
=> build(frontend): upgrade to Storybook 9

frontend/.storybook/preview.tsx
Fix the Storybook base URL on GitHub Pages.
=> fix(frontend): Storybook base URL

frontend/src/app/pages/GuidePage.tsx
Host CCRI technical methodology report on 'Guide' page.
=> Host technical report
